services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
      - ./app:/workspace
    ports:
      - "3000:3000"
    command: ["sleep", "infinity"]
    